sudo: required

  # # install Rust
  # - curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
  # - rustc --version

services:
  - docker

install:
  # clone LmcpGen
  - git clone https://github.com/afrl-rq/LmcpGen.git ../LmcpGen
  # tries to check out the same branch as the one we're building if it's
  # available, so that development can proceed in tandem
  - (cd ../LmcpGen; (git checkout $TRAVIS_BRANCH || true); ant jar)

script:
  - (cd docker/develop; ./01_buildImage_UxAS_build.sh && ./02_buildUxAS_WithDocker.sh && ./03_stopAndRemoveBuildContainer.sh && ./04_runUxAS_Tests.sh)
  - (cd docker/deploy; ./01_buildRun_Image.sh)
