# Global variables
language: python

python:
    - "3.7"
env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - INSTALL_DIR=$HOME/build_tools/install
    - CMAKE_BUILD_PARALLEL_LEVEL=1
os:
  - linux
dist:
  - bionic
git:
  submodules: false

# Cache directory that allows us to not download GNAT GPL every time, speeding
# up the process.
cache:
  directories:
    - $HOME/build_tools

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake
  - sudo apt-get install -y pkg-config
  - sudo apt-get install -y uuid-dev

install:
  - export PATH=$INSTALL_DIR/bin:$PATH
  - sh .travis-install.sh

script:
  # Build uxas
  - $TOOLS_DIR/OpenUxAS-bootstrap/anod-build uxas
  - $TOOLS_DIR/OpenUxAS-bootstrap/anod-build uxas --qualifier=scenario=gcov
  - eval `$TOOLS_DIR/OpenUxAS-bootstrap/anod-setenv uxas`
  - testsuite/run-tests