# Global variables
language: python

python:
    - "3.7"
env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - INSTALL_DIR=$HOME/build_tools/install
    - CMAKE_BUILD_PARALLEL_LEVEL=1
    - GNAT_INSTALLER=$TOOLS_DIR/gnat-community-installer
    - GNAT_LINUX_INSTALLER_URL=https://community.download.adacore.com/v1/0cd3e2a668332613b522d9612ffa27ef3eb0815b?filename=gnat-community-2019-20190517-x86_64-linux-bin
    # - FILES_TO_ANALYZE=uxas-comms-lmcp_net_client-service-automation_request_validation-spark.ads
os:
  - linux
dist:
  - bionic
git:
  submodules: false

# Cache directory that allows us to not download GNAT GPL every time, speeding
# up the process.
cache:
  directories:
    - $HOME/build_tools

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake
  - sudo apt-get install -y pkg-config
  - sudo apt-get install -y uuid-dev

install:
  - export PATH=$INSTALL_DIR/bin:$PATH
  - sh .travis-install.sh

script:
  # Build uxas
  - $TOOLS_DIR/OpenUxAS-bootstrap/anod-build uxas
  - $TOOLS_DIR/OpenUxAS-bootstrap/anod-build uxas-ada
  - $TOOLS_DIR/OpenUxAS-bootstrap/anod-build uxas --qualifier=scenario=gcov
  - $TOOLS_DIR/OpenUxAS-bootstrap/anod-build uxas-ada --qualifier=gcov
  - eval `$TOOLS_DIR/OpenUxAS-bootstrap/anod-setenv uxas --qualifier=scenario=gcov`
  - testsuite/run-tests
  # - eval `$TOOLS_DIR/OpenUxAS-bootstrap/anod-setenv uxas-ada --build-env`
  # - cd ada/arv-demo/src
  # - gnatprove -P ../afrl_ada_dev.gpr -u $FILES_TO_ANALYZE --level=2 --report=all -j0 --no-counterexample
