amase:
  scenario: Scenario_DistributedCooperation.xml

uxases:
  - config: cfgDistributedCooperation_1000.xml
    rundir: RUNDIR_1000

  - config: cfgDistributedCooperation_2000.xml
    rundir: RUNDIR_2000
