on: [push, pull_request]
name: Build
jobs:
  build:
    name: Build UxAS
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        component: [uxas]
        qualifier: [dev, scenario=gcov]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Check out OpenUxAS-bootstrap
        uses: actions/checkout@v2
        with:
          repository: AdaCore/OpenUxAS-bootstrap
          path: $HOME/bootstrap

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install anod dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install wheel 
      #     pip install zmq e3-core e3-testsuite
      #     sudo apt-get install -y uuid-dev

      - name: Bootstrap anod
        run: |
          $HOME/bootstrap/install/install-anod-venv -vv -y

      - name: Patch bootstrap
        run: |
          patch -d$HOME/bootstrap -p0 < $GITHUB_WORKSPACE/.github/bootstrap.patch
          cat $HOME/bootstrap/specs/config/repositories.yaml

      - name: Build with anod
        run: |
          eval "$( $HOME/bootstrap/install/install-anod-venv --printenv )"
          SHELL=/bin/bash $HOME/bootstrap/anod -v build ${{ matrix.component }} --qualifier=${{ matrix.qualifier}}
      
      - name: Run tests
        run: |
          eval "$( $HOME/bootstrap/install/install-anod-venv --printenv )"
          eval "$( $HOME/bootstrap/anod -v printenv ${{ matrix.component }} --qualifier=${{ matrix.qualifier }} )"
          echo $PATH
          $GITHUB_WORKSPACE/testsuite/run-tests
